--- 
title: "Analysis of single-cell RNA-seq data"
author: "Vladimir Kiselev, Tallulah Andrews and Martin Hemberg"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
always_allow_html: yes
---

# About the course

Recent technological advances have made it possible to obtain genome-wide transcriptome data from single cells using high-throughput sequencing (scRNA-seq). The advantage of scRNA-seq is that it makes it possible to address questions that are inaccessible using bulk RNA-seq technology. However, the computational analysis of scRNA-seq presents novel challenges, many of which remain unresolved today.

In this course we will be surveying the existing problems as well as the available computational and statistical frameworks available for the analysis of scRNA-seq. The approaches presented should be considered as our view on what is best practice for the data analysis and as new results are presented in the field, we aim to update the material presented here accordingly.

## Registration  

This course is being offered through the <a href="http://training.csx.cam.ac.uk/bioinformatics/" target="blank">Bioinformatics training</a> at the University of Cambridge. However, the material is meant to be free-standing and it is our aim that anyone who is interested in learning the basics of scRNA-seq analysis should be able to utilize this resource.

<a href="http://training.csx.cam.ac.uk/bioinformatics/event/1626698" target="blank">http://training.csx.cam.ac.uk/bioinformatics/event/1626698</a>

## GitHub
<a href="https://github.com/hemberg-lab/scRNA.seq.course" target="blank">https://github.com/hemberg-lab/scRNA.seq.course</a>

## License
<a href="http://creativecommons.org/licenses/by-nd/4.0" target="blank">Creative Commons Attribution-NoDerivatives 4.0 International License</a>

## Prerequisites

The course is intended for those who have basic familiarity with Unix and the R scripting language.

We will also assume that you are familiar with mapping and analysing bulk RNA-seq data as well as with the commonly available computational tools.

We recommend attending the [Introduction to RNA-seq and ChIP-seq data analysis](http://training.csx.cam.ac.uk/bioinformatics/event/1544785) or the [Analysis of high-throughput sequencing data with Bioconductor](http://training.csx.cam.ac.uk/bioinformatics/event/1614561) before attending this course.
